
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package GXML_ANALIZADORES;

/** CUP generated class containing symbol constants. */
public class Tabla_Simbolos_GXML_CUP {
  /* terminals */
  public static final int r_accionfinal = 55;
  public static final int s_cor_open = 11;
  public static final int s_div = 22;
  public static final int r_posy = 57;
  public static final int r_posx = 56;
  public static final int r_dato = 43;
  public static final int s_dot = 14;
  public static final int identificador = 7;
  public static final int s_dobledot = 13;
  public static final int r_texto = 40;
  public static final int booleano = 2;
  public static final int r_nombre = 61;
  public static final int s_compare = 27;
  public static final int cadena = 6;
  public static final int s_equal = 36;
  public static final int decimal = 4;
  public static final int r_numerico = 66;
  public static final int r_musica = 73;
  public static final int r_ventana = 38;
  public static final int s_greather = 30;
  public static final int r_accion = 71;
  public static final int s_and = 34;
  public static final int r_imagen = 75;
  public static final int r_path = 76;
  public static final int r_desplegable = 68;
  public static final int s_less_equal = 31;
  public static final int caracter = 5;
  public static final int s_or = 33;
  public static final int r_tamano = 63;
  public static final int s_greather_equal = 32;
  public static final int s_par_close = 18;
  public static final int s_less = 29;
  public static final int r_id = 49;
  public static final int contenido_tag = 8;
  public static final int s_increment = 25;
  public static final int s_minus = 20;
  public static final int r_ancho = 59;
  public static final int s_diferent = 28;
  public static final int r_maximo = 69;
  public static final int s_par_open = 17;
  public static final int r_textoarea = 67;
  public static final int r_control = 44;
  public static final int r_borde = 60;
  public static final int r_principal = 51;
  public static final int s_to = 23;
  public static final int r_defecto = 45;
  public static final int r_alto = 58;
  public static final int s_key_close = 10;
  public static final int EOF = 0;
  public static final int r_autoreproduccion = 77;
  public static final int r_listadatos = 42;
  public static final int s_key_open = 9;
  public static final int r_boton = 47;
  public static final int r_enviar = 48;
  public static final int r_contenedor = 39;
  public static final int s_dotcoma = 16;
  public static final int r_color = 53;
  public static final int s_not = 35;
  public static final int r_controlador = 41;
  public static final int r_minimo = 70;
  public static final int error = 1;
  public static final int r_negrita = 64;
  public static final int s_cor_close = 12;
  public static final int entero = 3;
  public static final int r_multimedia = 46;
  public static final int r_accioninicial = 54;
  public static final int s_mul = 21;
  public static final int s_mod = 24;
  public static final int r_video = 74;
  public static final int r_tipo = 50;
  public static final int r_referencia = 72;
  public static final int r_importar = 37;
  public static final int r_fuente = 62;
  public static final int r_secundaria = 52;
  public static final int r_cursiva = 65;
  public static final int s_decrement = 26;
  public static final int s_coma = 15;
  public static final int s_plus = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "booleano",
  "entero",
  "decimal",
  "caracter",
  "cadena",
  "identificador",
  "contenido_tag",
  "s_key_open",
  "s_key_close",
  "s_cor_open",
  "s_cor_close",
  "s_dobledot",
  "s_dot",
  "s_coma",
  "s_dotcoma",
  "s_par_open",
  "s_par_close",
  "s_plus",
  "s_minus",
  "s_mul",
  "s_div",
  "s_to",
  "s_mod",
  "s_increment",
  "s_decrement",
  "s_compare",
  "s_diferent",
  "s_less",
  "s_greather",
  "s_less_equal",
  "s_greather_equal",
  "s_or",
  "s_and",
  "s_not",
  "s_equal",
  "r_importar",
  "r_ventana",
  "r_contenedor",
  "r_texto",
  "r_controlador",
  "r_listadatos",
  "r_dato",
  "r_control",
  "r_defecto",
  "r_multimedia",
  "r_boton",
  "r_enviar",
  "r_id",
  "r_tipo",
  "r_principal",
  "r_secundaria",
  "r_color",
  "r_accioninicial",
  "r_accionfinal",
  "r_posx",
  "r_posy",
  "r_alto",
  "r_ancho",
  "r_borde",
  "r_nombre",
  "r_fuente",
  "r_tamano",
  "r_negrita",
  "r_cursiva",
  "r_numerico",
  "r_textoarea",
  "r_desplegable",
  "r_maximo",
  "r_minimo",
  "r_accion",
  "r_referencia",
  "r_musica",
  "r_video",
  "r_imagen",
  "r_path",
  "r_autoreproduccion"
  };
}

