
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package GXML_ANALIZADORES;

/** CUP generated class containing symbol constants. */
public class Tabla_Simbolos_GXML_CUP {
  /* terminals */
  public static final int r_nulo = 2;
  public static final int r_multimedia = 42;
  public static final int r_texto = 37;
  public static final int r_alto = 52;
  public static final int r_accionfinal = 49;
  public static final int r_contenedor = 36;
  public static final int r_posy = 51;
  public static final int r_borde = 54;
  public static final int r_posx = 50;
  public static final int s_to = 20;
  public static final int r_accion = 62;
  public static final int r_maximo = 60;
  public static final int identificador = 8;
  public static final int r_boton = 43;
  public static final int s_less = 26;
  public static final int r_accioninicial = 48;
  public static final int contenido_tag = 9;
  public static final int caracter = 6;
  public static final int s_not = 32;
  public static final int s_and = 31;
  public static final int r_ancho = 53;
  public static final int s_par_close = 15;
  public static final int r_defecto = 41;
  public static final int s_plus = 16;
  public static final int s_diferent = 25;
  public static final int s_div = 19;
  public static final int s_greather_equal = 29;
  public static final int s_minus = 17;
  public static final int r_referencia = 63;
  public static final int r_id = 45;
  public static final int r_control = 40;
  public static final int EOF = 0;
  public static final int s_dot = 12;
  public static final int error = 1;
  public static final int s_coma = 13;
  public static final int r_tipo = 46;
  public static final int entero = 5;
  public static final int r_importar = 34;
  public static final int s_key_close = 11;
  public static final int s_mul = 18;
  public static final int r_fuente = 56;
  public static final int s_compare = 24;
  public static final int r_enviar = 44;
  public static final int s_less_equal = 28;
  public static final int r_path = 64;
  public static final int r_dato = 39;
  public static final int s_mod = 21;
  public static final int s_increment = 22;
  public static final int r_autoreproduccion = 65;
  public static final int r_nombre = 55;
  public static final int s_greather = 27;
  public static final int s_par_open = 14;
  public static final int s_equal = 33;
  public static final int s_or = 30;
  public static final int r_ventana = 35;
  public static final int booleano = 3;
  public static final int s_decrement = 23;
  public static final int r_color = 47;
  public static final int s_key_open = 10;
  public static final int r_tamano = 57;
  public static final int r_minimo = 61;
  public static final int r_cursiva = 59;
  public static final int decimal = 4;
  public static final int cadena = 7;
  public static final int r_negrita = 58;
  public static final int r_listadatos = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "r_nulo",
  "booleano",
  "decimal",
  "entero",
  "caracter",
  "cadena",
  "identificador",
  "contenido_tag",
  "s_key_open",
  "s_key_close",
  "s_dot",
  "s_coma",
  "s_par_open",
  "s_par_close",
  "s_plus",
  "s_minus",
  "s_mul",
  "s_div",
  "s_to",
  "s_mod",
  "s_increment",
  "s_decrement",
  "s_compare",
  "s_diferent",
  "s_less",
  "s_greather",
  "s_less_equal",
  "s_greather_equal",
  "s_or",
  "s_and",
  "s_not",
  "s_equal",
  "r_importar",
  "r_ventana",
  "r_contenedor",
  "r_texto",
  "r_listadatos",
  "r_dato",
  "r_control",
  "r_defecto",
  "r_multimedia",
  "r_boton",
  "r_enviar",
  "r_id",
  "r_tipo",
  "r_color",
  "r_accioninicial",
  "r_accionfinal",
  "r_posx",
  "r_posy",
  "r_alto",
  "r_ancho",
  "r_borde",
  "r_nombre",
  "r_fuente",
  "r_tamano",
  "r_negrita",
  "r_cursiva",
  "r_maximo",
  "r_minimo",
  "r_accion",
  "r_referencia",
  "r_path",
  "r_autoreproduccion"
  };
}

