/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.io.BufferedReader;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Cristian Azurdia
 */
public class ExtemeEditor extends javax.swing.JFrame {
    
    private ArrayList<ObjetoEntrada> lista_objetos_entrada;
    private ObjetoEntrada entrada_actual;  
    
    public ExtemeEditor() {        
        initComponents();
        lista_objetos_entrada = new ArrayList<ObjetoEntrada>();
        this.agregar_pestaña();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jTPEntrada = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPConsola = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMArchivo = new javax.swing.JMenu();
        jMIAbrir = new javax.swing.JMenuItem();
        jMIGuardar = new javax.swing.JMenuItem();
        jMIGuardarComo = new javax.swing.JMenuItem();
        jMPestañas = new javax.swing.JMenu();
        jMINuevaPestaña = new javax.swing.JMenuItem();
        jMICerrarPestaña = new javax.swing.JMenuItem();
        jMEjecutar = new javax.swing.JMenu();
        jMErrores = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setDividerLocation(250);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setLeftComponent(jTPEntrada);

        jTPConsola.setBackground(new java.awt.Color(0, 0, 0));
        jTPConsola.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTPConsola.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTPConsola.setForeground(new java.awt.Color(102, 255, 102));
        jScrollPane1.setViewportView(jTPConsola);

        jSplitPane2.setRightComponent(jScrollPane1);

        jMArchivo.setText("Archivo");

        jMIAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMIAbrir.setText("Abrir");
        jMArchivo.add(jMIAbrir);

        jMIGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMIGuardar.setText("Guardar");
        jMArchivo.add(jMIGuardar);

        jMIGuardarComo.setText("Guardar Como...");
        jMArchivo.add(jMIGuardarComo);

        jMenuBar1.add(jMArchivo);

        jMPestañas.setText("Pestañas");

        jMINuevaPestaña.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMINuevaPestaña.setText("Nueva Pestaña");
        jMPestañas.add(jMINuevaPestaña);

        jMICerrarPestaña.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMICerrarPestaña.setText("Cerrar Pestaña");
        jMPestañas.add(jMICerrarPestaña);

        jMenuBar1.add(jMPestañas);

        jMEjecutar.setText("Ejecutar");
        jMEjecutar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMEjecutarMenuSelected(evt);
            }
        });
        jMEjecutar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMEjecutarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMEjecutar);

        jMErrores.setText("Errores");
        jMenuBar1.add(jMErrores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMEjecutarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMEjecutarMenuSelected
        
    }//GEN-LAST:event_jMEjecutarMenuSelected

    private void jMEjecutarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMEjecutarMouseClicked
        //JOptionPane.showMessageDialog(rootPane, "Holis!!");
        
        if(!entrada_actual.getJTEntrada().getText().equalsIgnoreCase("")){
            try
            {
                this.jTPConsola.setText("");
                FS_TABLA_SIMBOLOS.Tabla_Simbolos.getInstance().Limpiar();
                FS_ANALIZADORES.Lexico_FS lexico_fs = new FS_ANALIZADORES.Lexico_FS(new BufferedReader(new StringReader(entrada_actual.getJTEntrada().getText().toString())));
                FS_ANALIZADORES.Sintactico_FS sintactico_fs = new FS_ANALIZADORES.Sintactico_FS(lexico_fs);
                sintactico_fs.setObjetoEntrada(entrada_actual);
                sintactico_fs.parse();
                if(ERRORES.Tabla_Errores.getInstance().size() > 0)
                {
                    ERRORES.Ventana_Errores mostrar_error = new ERRORES.Ventana_Errores();
                    mostrar_error.show();
                }                  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"error: " + e.getMessage());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Ingrese un texto");
        }
    }//GEN-LAST:event_jMEjecutarMouseClicked

    public void agregar_pestaña()
    {
        //agregar el nuevo panel a la pestaña
        entrada_actual = new ObjetoEntrada();
        lista_objetos_entrada.add(entrada_actual);
        
        entrada_actual.setConsola(jTPConsola);
        //entrada_actual.setConsola_dasm(jEPConsola_Dasm);
        //entrada_actual.setPath_archivo(System.getProperty("user.dir"));
        //entrada_actual.setNombre_archivo("Nuevo_archivo_" + jTPEntrada.getComponentCount());
        //int seleccion = JOptionPane.showOptionDialog(this,"Seleccione opcion", "Selector de tipo de archivo",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null, new Object[] { "D++ dpp", "DracoSrcrip djs"}, "opcion 1");
        //if (seleccion == 0)
        //{
            //entrada_actual.setExtesion_archivo("dpp");
        //}
        //else if(seleccion == 1)
        //{
            //entrada_actual.setExtesion_archivo("djs");
        //}
        //else
        //{
            //entrada_actual.setExtesion_archivo("dpp");
        //}
        //entrada_actual.reiniciar_archivo_dasm();
        jTPEntrada.addTab("Nuevo_Archivo_" + jTPEntrada.getComponentCount() , new JScrollPane(entrada_actual.getJTEntrada()));
        jTPEntrada.setSelectedIndex(jTPEntrada.getComponentCount()- 1);        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtemeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtemeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtemeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtemeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtemeEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMArchivo;
    private javax.swing.JMenu jMEjecutar;
    private javax.swing.JMenu jMErrores;
    private javax.swing.JMenuItem jMIAbrir;
    private javax.swing.JMenuItem jMICerrarPestaña;
    private javax.swing.JMenuItem jMIGuardar;
    private javax.swing.JMenuItem jMIGuardarComo;
    private javax.swing.JMenuItem jMINuevaPestaña;
    private javax.swing.JMenu jMPestañas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextPane jTPConsola;
    private javax.swing.JTabbedPane jTPEntrada;
    // End of variables declaration//GEN-END:variables
}
