
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package FS_ANALIZADORES;

/** CUP generated class containing symbol constants. */
public class Tabla_Simbolos_FS_CUP {
  /* terminals */
  public static final int r_selecciona = 45;
  public static final int s_cor_open = 10;
  public static final int r_buscar = 55;
  public static final int s_div = 22;
  public static final int r_imprimir = 39;
  public static final int s_dot = 14;
  public static final int identificador = 7;
  public static final int r_detener = 41;
  public static final int s_dobledot = 13;
  public static final int booleano = 2;
  public static final int r_leergxml = 61;
  public static final int r_sino = 44;
  public static final int r_caso = 46;
  public static final int r_obteneretiqueta = 62;
  public static final int s_compare = 27;
  public static final int cadena = 6;
  public static final int r_map = 56;
  public static final int r_obtenernombre = 64;
  public static final int r_crearareatexto = 69;
  public static final int r_ascendente = 50;
  public static final int s_equal = 36;
  public static final int decimal = 4;
  public static final int r_invertir = 51;
  public static final int r_reduce = 57;
  public static final int s_greather = 30;
  public static final int r_retornar = 42;
  public static final int r_creardesplegable = 71;
  public static final int s_and = 34;
  public static final int s_less_equal = 31;
  public static final int caracter = 5;
  public static final int s_or = 33;
  public static final int r_crearboton = 72;
  public static final int s_greather_equal = 32;
  public static final int s_par_close = 18;
  public static final int s_less = 29;
  public static final int r_crearcajatexto = 68;
  public static final int r_crearventana = 65;
  public static final int s_increment = 25;
  public static final int s_minus = 20;
  public static final int s_diferent = 28;
  public static final int r_maximo = 52;
  public static final int r_clic = 76;
  public static final int s_par_open = 17;
  public static final int r_alguno = 59;
  public static final int r_crearvideo = 75;
  public static final int s_to = 23;
  public static final int r_defecto = 47;
  public static final int s_key_close = 9;
  public static final int r_crearimagen = 73;
  public static final int EOF = 0;
  public static final int s_key_open = 8;
  public static final int r_cerrar = 78;
  public static final int r_crearcontenedor = 66;
  public static final int s_dotcoma = 16;
  public static final int r_filtrar = 54;
  public static final int s_not = 35;
  public static final int r_crearcontrolnumerico = 70;
  public static final int r_minimo = 53;
  public static final int error = 1;
  public static final int r_todos = 58;
  public static final int r_cargar = 77;
  public static final int r_si = 43;
  public static final int s_cor_close = 11;
  public static final int entero = 3;
  public static final int r_obtenerid = 63;
  public static final int r_creartexto = 67;
  public static final int r_funcion = 48;
  public static final int s_mul = 21;
  public static final int s_mod = 24;
  public static final int s_ternario = 12;
  public static final int r_importar = 40;
  public static final int s_decrement = 26;
  public static final int r_descendente = 49;
  public static final int s_coma = 15;
  public static final int r_var = 38;
  public static final int r_creararray = 60;
  public static final int r_nulo = 37;
  public static final int s_plus = 19;
  public static final int r_crearreproductor = 74;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "booleano",
  "entero",
  "decimal",
  "caracter",
  "cadena",
  "identificador",
  "s_key_open",
  "s_key_close",
  "s_cor_open",
  "s_cor_close",
  "s_ternario",
  "s_dobledot",
  "s_dot",
  "s_coma",
  "s_dotcoma",
  "s_par_open",
  "s_par_close",
  "s_plus",
  "s_minus",
  "s_mul",
  "s_div",
  "s_to",
  "s_mod",
  "s_increment",
  "s_decrement",
  "s_compare",
  "s_diferent",
  "s_less",
  "s_greather",
  "s_less_equal",
  "s_greather_equal",
  "s_or",
  "s_and",
  "s_not",
  "s_equal",
  "r_nulo",
  "r_var",
  "r_imprimir",
  "r_importar",
  "r_detener",
  "r_retornar",
  "r_si",
  "r_sino",
  "r_selecciona",
  "r_caso",
  "r_defecto",
  "r_funcion",
  "r_descendente",
  "r_ascendente",
  "r_invertir",
  "r_maximo",
  "r_minimo",
  "r_filtrar",
  "r_buscar",
  "r_map",
  "r_reduce",
  "r_todos",
  "r_alguno",
  "r_creararray",
  "r_leergxml",
  "r_obteneretiqueta",
  "r_obtenerid",
  "r_obtenernombre",
  "r_crearventana",
  "r_crearcontenedor",
  "r_creartexto",
  "r_crearcajatexto",
  "r_crearareatexto",
  "r_crearcontrolnumerico",
  "r_creardesplegable",
  "r_crearboton",
  "r_crearimagen",
  "r_crearreproductor",
  "r_crearvideo",
  "r_clic",
  "r_cargar",
  "r_cerrar"
  };
}

