//mis entradas de pruega
imprimir("pruebas con numeros decimales");
imprimir(5+4.5);
imprimir(7.8+3);
imprimir(3.56+2.3);
imprimir("");
imprimir(5-4.5);
imprimir(7.8-3);
imprimir(3.56-2.3);
imprimir("");
imprimir(5*4.5);
imprimir(7.8*3);
imprimir(3.56*2.3);
imprimir("");
imprimir(5/4.5);
imprimir(7.8/3);
imprimir(3.56/2.3);
imprimir("");
imprimir(5^4.5);
imprimir(7.8^3);
imprimir(verdadero^1.2);
imprimir(4.5^verdadero);
imprimir(3.56^2.3);
imprimir("");
imprimir("");
imprimir("pruebas con numeros enteros");
imprimir(4+5);
imprimir("");
imprimir(4-5);
imprimir("");
imprimir(4*5);
imprimir("");
imprimir(4/5);
imprimir("");
imprimir(4^verdadero);
imprimir(verdadero^4);
imprimir(4^5);
imprimir("");
imprimir("");
imprimir("pruebas con cadenas");
imprimir(7+"hola");
imprimir("hola"+7);
imprimir(falso+".");
imprimir("es"+falso);
imprimir("hola" + "mundo");