//mis segundas fucking entradas de prueba
imprimir("Operador Mayor que");
imprimir(5>4);
imprimir(4.5>6);
imprimir("abc">"abc");
imprimir('a'>"a");
imprimir(97>'a');
imprimir("Operador Menor que");
imprimir(5<4);
imprimir(4.5<6);
imprimir("abc"<"abc");
imprimir('a'<"a");
imprimir(97<'a');
imprimir("Operador Mayor Igual que");
imprimir(5>=4);
imprimir(4.5>=6);
imprimir("abc">="abc");
imprimir('a'>="a");
imprimir(97>='a');
imprimir("Operador Menor Igual que");
imprimir(5<=4);
imprimir(4.5<=6);
imprimir("abc"<="abc");
imprimir('a'<="a");
imprimir(97<='a');
imprimir("Operador Igual que");
imprimir(5==4);
imprimir(4.5==6);
imprimir("abc"=="abc");
imprimir('a'=="a");
imprimir(97=='a');
imprimir("Operador Diferente que");
imprimir(5!=4);
imprimir(4.5!=6);
imprimir("abc"!="abc");
imprimir('a'!="a");
imprimir(97!='a');